# Generated by Django 3.2.7 on 2021-10-20 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authAppExample', '0008_alter_account_lastchangedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lastChangeDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
